@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
SET ASCII="#$%%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
SET PROGRAM="++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.------.--------.>+.>."
SET PROGRAM=!PROGRAM:~1,-1!
SET INPUT="A"
SET CURRENT=0
SET NESTLED=0
SET MEMPTR=0
SET MEMSIZE=30000
FOR /F %%A IN ('"PROMPT $H &ECHO ON &FOR %%B IN (1) DO REM"') DO SET BS=%%A
:LOOP
SET INSTR=!PROGRAM:~%CURRENT%,1!
IF [!INSTR!] == [] GOTO EXIT
IF NOT DEFINED MEM[!MEMPTR!] (
	SET MEM[!MEMPTR!]=0
)
IF !INSTR!==+ (
	IF !MEM[%MEMPTR%]! GEQ 255 (
		SET MEM[!MEMPTR!]=0
	) ELSE (
		SET /A MEM[!MEMPTR!]=MEM[!MEMPTR!]+1
	)
)
IF !INSTR!==- (
	IF !MEM[%MEMPTR%]! LEQ 0 (
		SET MEM[!MEMPTR!]=255
	) ELSE (
		SET /A MEM[!MEMPTR!]=MEM[!MEMPTR!]-1
	)
)
IF !INSTR!==^> (
	IF !MEMPTR! GEQ %MEMSIZE% (
		SET MEMPTR=0
	) ELSE (
		SET /A MEMPTR=!MEMPTR!+1
	)
)
IF !INSTR!==^< (
	IF !MEMPTR! LEQ 0 (
		SET MEMPTR=%MEMSIZE%
	) ELSE (
		SET /A MEMPTR=!MEMPTR!-1
	)
)
IF !INSTR!==^, (
	CALL :GETCHAR
)
IF !INSTR!==. (
	IF !MEM[%MEMPTR%]! GEQ 34 (
		CALL :SETCHAR
	) ELSE (
		IF !MEM[%MEMPTR%]!==32 <NUL SET /P=.%BS% 
		IF !MEM[%MEMPTR%]!==33 <NUL SET /P=^^!
		IF !MEM[%MEMPTR%]!==10 ECHO.
	)
)
IF !INSTR!==[ (
	IF !MEM[%MEMPTR%]!==0 (
		:WHILESTARTLOOP
		SET INSTR=!PROGRAM:~%CURRENT%,1!
		IF !INSTR!==[ SET /A NESTLED=!NESTLED!+1
		IF !INSTR!==] SET /A NESTLED=!NESTLED!-1
		SET /A CURRENT=!CURRENT!+1
		IF [!INSTR!] == [] GOTO ERROR
		IF NOT !NESTLED!==0 GOTO WHILESTARTLOOP
	)
)
IF !INSTR!==] (
	IF NOT !MEM[%MEMPTR%]!==0 (
		:WHILEENDLOOP
		SET INSTR=!PROGRAM:~%CURRENT%,1!
		IF !INSTR!==[ SET /A NESTLED=!NESTLED!+1
		IF !INSTR!==] SET /A NESTLED=!NESTLED!-1
		SET /A CURRENT=!CURRENT!-1
		IF [!INSTR!] == [] GOTO ERROR
		IF NOT !NESTLED!==0 GOTO WHILEENDLOOP
	)
)
SET /A CURRENT=!CURRENT!+1
GOTO LOOP
:SETCHAR
SET /A CHAR=!MEM[%MEMPTR%]!-34
<NUL SET /P=!ASCII:~%CHAR%,1!
GOTO :EOF
:GETCHAR
SET RESULT=0
FOR /L %%I IN (0,1,92) DO (
	SET INDEX=%%I
	CALL :TESTCHAR
)
:DONE
SET /A MEM[%MEMPTR%]=!RESULT!+34
SET INPUT="!INPUT:~2,-1!"
GOTO :EOF
:TESTCHAR
SET CHAR1=!ASCII:~%INDEX%,1!
SET CHAR2=!INPUT:~1,1!
IF [!CHAR1!]==[!CHAR2!] (
	SET RESULT=%INDEX%
	GOTO :DONE
)
GOTO :EOF
:ERROR
ECHO ERROR: UNBALANCED BRACKETS
:EXIT
PAUSE
ENDLOCAL
